version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build